### ISSUE TITLE
Update PR description instead of commenting

### ISSUE THREAD

**Issue by Nfinished** [phwt/sonarqube-quality-gate-action#5]
Hi, would you accept a pr adding this option? Willing to contribute.

**Comment by phwt** [comment]
Hi, this would be a great alternative for displaying an output. Any contribution is appreciated!

**Comment by Nfinished** [comment]
Cool, I'm thinking we could either replace `disable-pr-comment` with a `display-mode` that accepts either `'comment'` or `'description'` (major version)

Or add an additional `update-description` boolean which defaults to `false`.

wdyt?

**Comment by phwt** [comment]
Maybe something like `output-type` with the option of `'comment'`, `'description'`, and `'disable'`? Then deprecate the `disable-pr-comment` option.

**Comment by Nfinished** [comment]
Sounds good
